apiVersion: v1
kind: LimitRange
metadata:
  name: lab4
spec:
  limits:
    - default:
        memory: 256Mi
        cpu: 250m
      defaultRequest:
        cpu: 125m
        memory: 64Mi
      type: Container
