---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: lab3
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
  namespace: lab3
spec:
  containers:
    - name: busybox-container
      image: busybox
      command:
        [
          "/bin/sh",
          "-c",
          "while true; do date >> /var/log/date.log; sleep 5; done",
        ]
      volumeMounts:
        - name: log-volume
          mountPath: /var/log
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: log-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: log-volume
      hostPath:
        path: /var/log
